name 'apache'
maintainer 'Luis Muñiz'
maintainer_email 'lmuniz@pue.es'
license 'all_rights'
description 'Instala y arranca un servidor Apache'
long_description 'Instala y arranca un servidor Apache'
version '0.2.0'
